name: CI - Workflow
on:
  push:
    branches: [master,main]
  pull_request:
    branches: [master,main]
env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.7.1"
jobs:
  install-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
