name: CI - Workflow
on:
  push:
    branches: [master,main]
  pull_request:
    branches: [master,main]
jobs:
  install-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World" 
